### ISSUE TITLE
BestFitLine doesn't work with DataLoader-Plugin

### ISSUE THREAD

**Issue by malmi** [amcharts/tools#8]
The BestFitLine-plugin doesn't work with the DataLoader-plugin. It would be awesome if it does in a future release. Thanks.

**Comment by b-nik** [comment]
Posting in case other people might find it useful.

This works fine with DataLoader but you need to call it specifically after loading your data, since the plugin itself only fires at init time.

So add this line whenever your data is loaded:
`    AmCharts.bestFitLineProcess( chart, false );
`

and you're set. The boolean parameter basically controls if you want it to call validate or not.
